FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV SCANNER_IP=127.0.0.1
ENV SCANNER_PORT=9100
ENV MQTT_BROKER=localhost
ENV MQTT_PORT=1883
ENV MQTT_TOPIC=thetoplevel/codeit/scanner

CMD ["python", "src/main.py"]
