from typing import Dict
from typing import Dict, List, Tuple, Any

class GS1AIHandler:
    def __init__(self):
        self.ai_definitions = self.load_ai_definitions()

    def load_ai_definitions(self) -> Dict[str, Dict[str, any]]:
        # This method loads all GS1 AI definitions
        # Updated with the complete list of AIs provided
        ai_definitions = {
            "00": {"title": "SSCC", "length": 18, "description": "Serial Shipping Container Code"},
            "01": {"title": "GTIN", "length": 14, "description": "Global Trade Item Number"},
            "02": {"title": "CONTENT", "length": 14, "description": "Identification of trade items contained in a logistic unit"},
            "10": {"title": "BATCH/LOT", "length": None, "description": "Batch or lot number"},
            "11": {"title": "PROD DATE", "length": 6, "description": "Production date (YYMMDD)"},
            "12": {"title": "DUE DATE", "length": 6, "description": "Due date for amount on payment slip (YYMMDD)"},
            "13": {"title": "PACK DATE", "length": 6, "description": "Packaging date (YYMMDD)"},
            "15": {"title": "BEST BEFORE", "length": 6, "description": "Best before date (YYMMDD)"},
            "16": {"title": "SELL BY", "length": 6, "description": "Sell by date (YYMMDD)"},
            "17": {"title": "EXPIRY", "length": 6, "description": "Expiration date (YYMMDD)"},
            "20": {"title": "VARIANT", "length": 2, "description": "Internal product variant"},
            "21": {"title": "SERIAL", "length": None, "description": "Serial number"},
            "22": {"title": "CPV", "length": None, "description": "Consumer product variant"},
            "235": {"title": "TPX", "length": None, "description": "Third Party Controlled, Serialised Extension of Global Trade Item Number (GTIN)"},
            "240": {"title": "ADDITIONAL ID", "length": None, "description": "Additional product identification assigned by the manufacturer"},
            "241": {"title": "CUST. PART No.", "length": None, "description": "Customer part number"},
            "242": {"title": "MTO VARIANT", "length": None, "description": "Made-to-Order variation number"},
            "243": {"title": "PCN", "length": None, "description": "Packaging component number"},
            "250": {"title": "SECONDARY SERIAL", "length": None, "description": "Secondary serial number"},
            "251": {"title": "REF. TO SOURCE", "length": None, "description": "Reference to source entity"},
            "253": {"title": "GDTI", "length": None, "description": "Global Document Type Identifier (GDTI)"},
            "254": {"title": "GLN EXTENSION COMPONENT", "length": None, "description": "Global Location Number (GLN) extension component"},
            "255": {"title": "GCN", "length": None, "description": "Global Coupon Number (GCN)"},
            "30": {"title": "VAR. COUNT", "length": None, "description": "Variable count of items (variable measure trade item)"},
            "3100": {"title": "NET WEIGHT (kg)", "length": 6, "description": "Net weight, kilograms (variable measure trade item)"},
            "3101": {"title": "NET WEIGHT (kg)", "length": 6, "description": "Net weight, kilograms (variable measure trade item)"},
            "3102": {"title": "NET WEIGHT (kg)", "length": 6, "description": "Net weight, kilograms (variable measure trade item)"},
            "3103": {"title": "NET WEIGHT (kg)", "length": 6, "description": "Net weight, kilograms (variable measure trade item)"},
            "3104": {"title": "NET WEIGHT (kg)", "length": 6, "description": "Net weight, kilograms (variable measure trade item)"},
            "3105": {"title": "NET WEIGHT (kg)", "length": 6, "description": "Net weight, kilograms (variable measure trade item)"},
            "3110": {"title": "LENGTH (m)", "length": 6, "description": "Length or first dimension, metres (variable measure trade item)"},
            "3111": {"title": "LENGTH (m)", "length": 6, "description": "Length or first dimension, metres (variable measure trade item)"},
            "3112": {"title": "LENGTH (m)", "length": 6, "description": "Length or first dimension, metres (variable measure trade item)"},
            "3113": {"title": "LENGTH (m)", "length": 6, "description": "Length or first dimension, metres (variable measure trade item)"},
            "3114": {"title": "LENGTH (m)", "length": 6, "description": "Length or first dimension, metres (variable measure trade item)"},
            "3115": {"title": "LENGTH (m)", "length": 6, "description": "Length or first dimension, metres (variable measure trade item)"},
            "3120": {"title": "WIDTH (m)", "length": 6, "description": "Width, diameter, or second dimension, metres (variable measure trade item)"},
            "3121": {"title": "WIDTH (m)", "length": 6, "description": "Width, diameter, or second dimension, metres (variable measure trade item)"},
            "3122": {"title": "WIDTH (m)", "length": 6, "description": "Width, diameter, or second dimension, metres (variable measure trade item)"},
            "3123": {"title": "WIDTH (m)", "length": 6, "description": "Width, diameter, or second dimension, metres (variable measure trade item)"},
            "3124": {"title": "WIDTH (m)", "length": 6, "description": "Width, diameter, or second dimension, metres (variable measure trade item)"},
            "3125": {"title": "WIDTH (m)", "length": 6, "description": "Width, diameter, or second dimension, metres (variable measure trade item)"},
            "3130": {"title": "HEIGHT (m)", "length": 6, "description": "Depth, thickness, height, or third dimension, metres (variable measure trade item)"},
            "3131": {"title": "HEIGHT (m)", "length": 6, "description": "Depth, thickness, height, or third dimension, metres (variable measure trade item)"},
            "3132": {"title": "HEIGHT (m)", "length": 6, "description": "Depth, thickness, height, or third dimension, metres (variable measure trade item)"},
            "3133": {"title": "HEIGHT (m)", "length": 6, "description": "Depth, thickness, height, or third dimension, metres (variable measure trade item)"},
            "3134": {"title": "HEIGHT (m)", "length": 6, "description": "Depth, thickness, height, or third dimension, metres (variable measure trade item)"},
            "3135": {"title": "HEIGHT (m)", "length": 6, "description": "Depth, thickness, height, or third dimension, metres (variable measure trade item)"},
            "3140": {"title": "AREA (m²)", "length": 6, "description": "Area, square metres (variable measure trade item)"},
            "3141": {"title": "AREA (m²)", "length": 6, "description": "Area, square metres (variable measure trade item)"},
            "3142": {"title": "AREA (m²)", "length": 6, "description": "Area, square metres (variable measure trade item)"},
            "3143": {"title": "AREA (m²)", "length": 6, "description": "Area, square metres (variable measure trade item)"},
            "3144": {"title": "AREA (m²)", "length": 6, "description": "Area, square metres (variable measure trade item)"},
            "3145": {"title": "AREA (m²)", "length": 6, "description": "Area, square metres (variable measure trade item)"},
            "3150": {"title": "NET VOLUME (l)", "length": 6, "description": "Net volume, litres (variable measure trade item)"},
            "3151": {"title": "NET VOLUME (l)", "length": 6, "description": "Net volume, litres (variable measure trade item)"},
            "3152": {"title": "NET VOLUME (l)", "length": 6, "description": "Net volume, litres (variable measure trade item)"},
            "3153": {"title": "NET VOLUME (l)", "length": 6, "description": "Net volume, litres (variable measure trade item)"},
            "3154": {"title": "NET VOLUME (l)", "length": 6, "description": "Net volume, litres (variable measure trade item)"},
            "3155": {"title": "NET VOLUME (l)", "length": 6, "description": "Net volume, litres (variable measure trade item)"},
            "3160": {"title": "NET VOLUME (m³)", "length": 6, "description": "Net volume, cubic metres (variable measure trade item)"},
            "3161": {"title": "NET VOLUME (m³)", "length": 6, "description": "Net volume, cubic metres (variable measure trade item)"},
            "3162": {"title": "NET VOLUME (m³)", "length": 6, "description": "Net volume, cubic metres (variable measure trade item)"},
            "3163": {"title": "NET VOLUME (m³)", "length": 6, "description": "Net volume, cubic metres (variable measure trade item)"},
            "3164": {"title": "NET VOLUME (m³)", "length": 6, "description": "Net volume, cubic metres (variable measure trade item)"},
            "3165": {"title": "NET VOLUME (m³)", "length": 6, "description": "Net volume, cubic metres (variable measure trade item)"},
            "3200": {"title": "NET WEIGHT (lb)", "length": 6, "description": "Net weight, pounds (variable measure trade item)"},
            "3201": {"title": "NET WEIGHT (lb)", "length": 6, "description": "Net weight, pounds (variable measure trade item)"},
            "3202": {"title": "NET WEIGHT (lb)", "length": 6, "description": "Net weight, pounds (variable measure trade item)"},
            "3203": {"title": "NET WEIGHT (lb)", "length": 6, "description": "Net weight, pounds (variable measure trade item)"},
            "3204": {"title": "NET WEIGHT (lb)", "length": 6, "description": "Net weight, pounds (variable measure trade item)"},
            "3205": {"title": "NET WEIGHT (lb)", "length": 6, "description": "Net weight, pounds (variable measure trade item)"},
            "3210": {"title": "LENGTH (in)", "length": 6, "description": "Length or first dimension, inches (variable measure trade item)"},
            "3211": {"title": "LENGTH (in)", "length": 6, "description": "Length or first dimension, inches (variable measure trade item)"},
            "3212": {"title": "LENGTH (in)", "length": 6, "description": "Length or first dimension, inches (variable measure trade item)"},
            "3213": {"title": "LENGTH (in)", "length": 6, "description": "Length or first dimension, inches (variable measure trade item)"},
            "3214": {"title": "LENGTH (in)", "length": 6, "description": "Length or first dimension, inches (variable measure trade item)"},
            "3215": {"title": "LENGTH (in)", "length": 6, "description": "Length or first dimension, inches (variable measure trade item)"},
            "3220": {"title": "LENGTH (ft)", "length": 6, "description": "Length or first dimension, feet (variable measure trade item)"},
            "3221": {"title": "LENGTH (ft)", "length": 6, "description": "Length or first dimension, feet (variable measure trade item)"},
            "3222": {"title": "LENGTH (ft)", "length": 6, "description": "Length or first dimension, feet (variable measure trade item)"},
            "3223": {"title": "LENGTH (ft)", "length": 6, "description": "Length or first dimension, feet (variable measure trade item)"},
            "3224": {"title": "LENGTH (ft)", "length": 6, "description": "Length or first dimension, feet (variable measure trade item)"},
            "3225": {"title": "LENGTH (ft)", "length": 6, "description": "Length or first dimension, feet (variable measure trade item)"},
            "3230": {"title": "LENGTH (yd)", "length": 6, "description": "Length or first dimension, yards (variable measure trade item)"},
            "3231": {"title": "LENGTH (yd)", "length": 6, "description": "Length or first dimension, yards (variable measure trade item)"},
            "3232": {"title": "LENGTH (yd)", "length": 6, "description": "Length or first dimension, yards (variable measure trade item)"},
            "3233": {"title": "LENGTH (yd)", "length": 6, "description": "Length or first dimension, yards (variable measure trade item)"},
            "3234": {"title": "LENGTH (yd)", "length": 6, "description": "Length or first dimension, yards (variable measure trade item)"},
            "3235": {"title": "LENGTH (yd)", "length": 6, "description": "Length or first dimension, yards (variable measure trade item)"},
            "3240": {"title": "WIDTH (in)", "length": 6, "description": "Width, diameter, or second dimension, inches (variable measure trade item)"},
            "3241": {"title": "WIDTH (in)", "length": 6, "description": "Width, diameter, or second dimension, inches (variable measure trade item)"},
            "3242": {"title": "WIDTH (in)", "length": 6, "description": "Width, diameter, or second dimension, inches (variable measure trade item)"},
            "3243": {"title": "WIDTH (in)", "length": 6, "description": "Width, diameter, or second dimension, inches (variable measure trade item)"},
            "3244": {"title": "WIDTH (in)", "length": 6, "description": "Width, diameter, or second dimension, inches (variable measure trade item)"},
            "3245": {"title": "WIDTH (in)", "length": 6, "description": "Width, diameter, or second dimension, inches (variable measure trade item)"},
            "3250": {"title": "WIDTH (ft)", "length": 6, "description": "Width, diameter, or second dimension, feet (variable measure trade item)"},
            "3251": {"title": "WIDTH (ft)", "length": 6, "description": "Width, diameter, or second dimension, feet (variable measure trade item)"},
            "3252": {"title": "WIDTH (ft)", "length": 6, "description": "Width, diameter, or second dimension, feet (variable measure trade item)"},
            "3253": {"title": "WIDTH (ft)", "length": 6, "description": "Width, diameter, or second dimension, feet (variable measure trade item)"},
            "3254": {"title": "WIDTH (ft)", "length": 6, "description": "Width, diameter, or second dimension, feet (variable measure trade item)"},
            "3255": {"title": "WIDTH (ft)", "length": 6, "description": "Width, diameter, or second dimension, feet (variable measure trade item)"},
            "3260": {"title": "WIDTH (yd)", "length": 6, "description": "Width, diameter, or second dimension, yards (variable measure trade item)"},
            "3261": {"title": "WIDTH (yd)", "length": 6, "description": "Width, diameter, or second dimension, yards (variable measure trade item)"},
            "3262": {"title": "WIDTH (yd)", "length": 6, "description": "Width, diameter, or second dimension, yards (variable measure trade item)"},
            "3263": {"title": "WIDTH (yd)", "length": 6, "description": "Width, diameter, or second dimension, yards (variable measure trade item)"},
            "3264": {"title": "WIDTH (yd)", "length": 6, "description": "Width, diameter, or second dimension, yards (variable measure trade item)"},
            "3265": {"title": "WIDTH (yd)", "length": 6, "description": "Width, diameter, or second dimension, yards (variable measure trade item)"},
            "3270": {"title": "HEIGHT (in)", "length": 6, "description": "Depth, thickness, height, or third dimension, inches (variable measure trade item)"},
            "3271": {"title": "HEIGHT (in)", "length": 6, "description": "Depth, thickness, height, or third dimension, inches (variable measure trade item)"},
            "3272": {"title": "HEIGHT (in)", "length": 6, "description": "Depth, thickness, height, or third dimension, inches (variable measure trade item)"},
            "3273": {"title": "HEIGHT (in)", "length": 6, "description": "Depth, thickness, height, or third dimension, inches (variable measure trade item)"},
            "3274": {"title": "HEIGHT (in)", "length": 6, "description": "Depth, thickness, height, or third dimension, inches (variable measure trade item)"},
            "3275": {"title": "HEIGHT (in)", "length": 6, "description": "Depth, thickness, height, or third dimension, inches (variable measure trade item)"},
            "3280": {"title": "HEIGHT (ft)", "length": 6, "description": "Depth, thickness, height, or third dimension, feet (variable measure trade item)"},
            "3281": {"title": "HEIGHT (ft)", "length": 6, "description": "Depth, thickness, height, or third dimension, feet (variable measure trade item)"},
            "3282": {"title": "HEIGHT (ft)", "length": 6, "description": "Depth, thickness, height, or third dimension, feet (variable measure trade item)"},
            "3283": {"title": "HEIGHT (ft)", "length": 6, "description": "Depth, thickness, height, or third dimension, feet (variable measure trade item)"},
            "3284": {"title": "HEIGHT (ft)", "length": 6, "description": "Depth, thickness, height, or third dimension, feet (variable measure trade item)"},
            "3285": {"title": "HEIGHT (ft)", "length": 6, "description": "Depth, thickness, height, or third dimension, feet (variable measure trade item)"},
            "3290": {"title": "HEIGHT (yd)", "length": 6, "description": "Depth, thickness, height, or third dimension, yards (variable measure trade item)"},
            "3291": {"title": "HEIGHT (yd)", "length": 6, "description": "Depth, thickness, height, or third dimension, yards (variable measure trade item)"},
            "3292": {"title": "HEIGHT (yd)", "length": 6, "description": "Depth, thickness, height, or third dimension, yards (variable measure trade item)"},
            "3293": {"title": "HEIGHT (yd)", "length": 6, "description": "Depth, thickness, height, or third dimension, yards (variable measure trade item)"},
            "3294": {"title": "HEIGHT (yd)", "length": 6, "description": "Depth, thickness, height, or third dimension, yards (variable measure trade item)"},
            "3295": {"title": "HEIGHT (yd)", "length": 6, "description": "Depth, thickness, height, or third dimension, yards (variable measure trade item)"},
            "3300": {"title": "GROSS WEIGHT (kg)", "length": 6, "description": "Logistic weight, kilograms"},
            "3301": {"title": "GROSS WEIGHT (kg)", "length": 6, "description": "Logistic weight, kilograms"},
            "3302": {"title": "GROSS WEIGHT (kg)", "length": 6, "description": "Logistic weight, kilograms"},
            "3303": {"title": "GROSS WEIGHT (kg)", "length": 6, "description": "Logistic weight, kilograms"},
            "3304": {"title": "GROSS WEIGHT (kg)", "length": 6, "description": "Logistic weight, kilograms"},
            "3305": {"title": "GROSS WEIGHT (kg)", "length": 6, "description": "Logistic weight, kilograms"},
            "3310": {"title": "LENGTH (m), log", "length": 6, "description": "Length or first dimension, metres, logistic unit"},
            "3311": {"title": "LENGTH (m), log", "length": 6, "description": "Length or first dimension, metres, logistic unit"},
            "3312": {"title": "LENGTH (m), log", "length": 6, "description": "Length or first dimension, metres, logistic unit"},
            "3313": {"title": "LENGTH (m), log", "length": 6, "description": "Length or first dimension, metres, logistic unit"},
            "3314": {"title": "LENGTH (m), log", "length": 6, "description": "Length or first dimension, metres, logistic unit"},
            "3315": {"title": "LENGTH (m), log", "length": 6, "description": "Length or first dimension, metres, logistic unit"},
            "3320": {"title": "WIDTH (m), log", "length": 6, "description": "Width, diameter, or second dimension, metres, logistic unit"},
            "3321": {"title": "WIDTH (m), log", "length": 6, "description": "Width, diameter, or second dimension, metres, logistic unit"},
            "3322": {"title": "WIDTH (m), log", "length": 6, "description": "Width, diameter, or second dimension, metres, logistic unit"},
            "3323": {"title": "WIDTH (m), log", "length": 6, "description": "Width, diameter, or second dimension, metres, logistic unit"},
            "3324": {"title": "WIDTH (m), log", "length": 6, "description": "Width, diameter, or second dimension, metres, logistic unit"},
            "3325": {"title": "WIDTH (m), log", "length": 6, "description": "Width, diameter, or second dimension, metres, logistic unit"},
            "3330": {"title": "HEIGHT (m), log", "length": 6, "description": "Depth, thickness, height, or third dimension, metres, logistic unit"},
            "3331": {"title": "HEIGHT (m), log", "length": 6, "description": "Depth, thickness, height, or third dimension, metres, logistic unit"},
            "3332": {"title": "HEIGHT (m), log", "length": 6, "description": "Depth, thickness, height, or third dimension, metres, logistic unit"},
            "3333": {"title": "HEIGHT (m), log", "length": 6, "description": "Depth, thickness, height, or third dimension, metres, logistic unit"},
            "3334": {"title": "HEIGHT (m), log", "length": 6, "description": "Depth, thickness, height, or third dimension, metres, logistic unit"},
            "3335": {"title": "HEIGHT (m), log", "length": 6, "description": "Depth, thickness, height, or third dimension, metres, logistic unit"},
            "3340": {"title": "AREA (m²), log", "length": 6, "description": "Area, square metres, logistic unit"},
            "3341": {"title": "AREA (m²), log", "length": 6, "description": "Area, square metres, logistic unit"},
            "3342": {"title": "AREA (m²), log", "length": 6, "description": "Area, square metres, logistic unit"},
            "3343": {"title": "AREA (m²), log", "length": 6, "description": "Area, square metres, logistic unit"},
            "3344": {"title": "AREA (m²), log", "length": 6, "description": "Area, square metres, logistic unit"},
            "3345": {"title": "AREA (m²), log", "length": 6, "description": "Area, square metres, logistic unit"},
            "3350": {"title": "VOLUME (l), log", "length": 6, "description": "Logistic volume, litres"},
            "3351": {"title": "VOLUME (l), log", "length": 6, "description": "Logistic volume, litres"},
            "3352": {"title": "VOLUME (l), log", "length": 6, "description": "Logistic volume, litres"},
            "3353": {"title": "VOLUME (l), log", "length": 6, "description": "Logistic volume, litres"},
            "3354": {"title": "VOLUME (l), log", "length": 6, "description": "Logistic volume, litres"},
            "3355": {"title": "VOLUME (l), log", "length": 6, "description": "Logistic volume, litres"},
            "3360": {"title": "VOLUME (m³), log", "length": 6, "description": "Logistic volume, cubic metres"},
            "3361": {"title": "VOLUME (m³), log", "length": 6, "description": "Logistic volume, cubic metres"},
            "3362": {"title": "VOLUME (m³), log", "length": 6, "description": "Logistic volume, cubic metres"},
            "3363": {"title": "VOLUME (m³), log", "length": 6, "description": "Logistic volume, cubic metres"},
            "3364": {"title": "VOLUME (m³), log", "length": 6, "description": "Logistic volume, cubic metres"},
            "3365": {"title": "VOLUME (m³), log", "length": 6, "description": "Logistic volume, cubic metres"},
            "3370": {"title": "KG PER m²", "length": 6, "description": "Kilograms per square metre"},
            "3371": {"title": "KG PER m²", "length": 6, "description": "Kilograms per square metre"},
            "3372": {"title": "KG PER m²", "length": 6, "description": "Kilograms per square metre"},
            "3373": {"title": "KG PER m²", "length": 6, "description": "Kilograms per square metre"},
            "3374": {"title": "KG PER m²", "length": 6, "description": "Kilograms per square metre"},
            "3375": {"title": "KG PER m²", "length": 6, "description": "Kilograms per square metre"},
            "3400": {"title": "GROSS WEIGHT (lb)", "length": 6, "description": "Logistic weight, pounds"},
            "3401": {"title": "GROSS WEIGHT (lb)", "length": 6, "description": "Logistic weight, pounds"},
            "3402": {"title": "GROSS WEIGHT (lb)", "length": 6, "description": "Logistic weight, pounds"},
            "3403": {"title": "GROSS WEIGHT (lb)", "length": 6, "description": "Logistic weight, pounds"},
            "3404": {"title": "GROSS WEIGHT (lb)", "length": 6, "description": "Logistic weight, pounds"},
            "3405": {"title": "GROSS WEIGHT (lb)", "length": 6, "description": "Logistic weight, pounds"},
            "3410": {"title": "LENGTH (in), log", "length": 6, "description": "Length or first dimension, inches, logistic unit"},
            "3411": {"title": "LENGTH (in), log", "length": 6, "description": "Length or first dimension, inches, logistic unit"},
            "3412": {"title": "LENGTH (in), log", "length": 6, "description": "Length or first dimension, inches, logistic unit"},
            "3413": {"title": "LENGTH (in), log", "length": 6, "description": "Length or first dimension, inches, logistic unit"},
            "3414": {"title": "LENGTH (in), log", "length": 6, "description": "Length or first dimension, inches, logistic unit"},
            "3415": {"title": "LENGTH (in), log", "length": 6, "description": "Length or first dimension, inches, logistic unit"},
            "3420": {"title": "LENGTH (ft), log", "length": 6, "description": "Length or first dimension, feet, logistic unit"},
            "3421": {"title": "LENGTH (ft), log", "length": 6, "description": "Length or first dimension, feet, logistic unit"},
            "3422": {"title": "LENGTH (ft), log", "length": 6, "description": "Length or first dimension, feet, logistic unit"},
            "3423": {"title": "LENGTH (ft), log", "length": 6, "description": "Length or first dimension, feet, logistic unit"},
            "3424": {"title": "LENGTH (ft), log", "length": 6, "description": "Length or first dimension, feet, logistic unit"},
            "3425": {"title": "LENGTH (ft), log", "length": 6, "description": "Length or first dimension, feet, logistic unit"},
            "3430": {"title": "LENGTH (yd), log", "length": 6, "description": "Length or first dimension, yards, logistic unit"},
            "3431": {"title": "LENGTH (yd), log", "length": 6, "description": "Length or first dimension, yards, logistic unit"},
            "3432": {"title": "LENGTH (yd), log", "length": 6, "description": "Length or first dimension, yards, logistic unit"},
            "3433": {"title": "LENGTH (yd), log", "length": 6, "description": "Length or first dimension, yards, logistic unit"},
            "3434": {"title": "LENGTH (yd), log", "length": 6, "description": "Length or first dimension, yards, logistic unit"},
            "3435": {"title": "LENGTH (yd), log", "length": 6, "description": "Length or first dimension, yards, logistic unit"},
            "3440": {"title": "WIDTH (in), log", "length": 6, "description": "Width, diameter, or second dimension, inches, logistic unit"},
            "3441": {"title": "WIDTH (in), log", "length": 6, "description": "Width, diameter, or second dimension, inches, logistic unit"},
            "3442": {"title": "WIDTH (in), log", "length": 6, "description": "Width, diameter, or second dimension, inches, logistic unit"},
            "3443": {"title": "WIDTH (in), log", "length": 6, "description": "Width, diameter, or second dimension, inches, logistic unit"},
            "3444": {"title": "WIDTH (in), log", "length": 6, "description": "Width, diameter, or second dimension, inches, logistic unit"},
            "3445": {"title": "WIDTH (in), log", "length": 6, "description": "Width, diameter, or second dimension, inches, logistic unit"},
            "3450": {"title": "WIDTH (ft), log", "length": 6, "description": "Width, diameter, or second dimension, feet, logistic unit"},
            "3451": {"title": "WIDTH (ft), log", "length": 6, "description": "Width, diameter, or second dimension, feet, logistic unit"},
            "3452": {"title": "WIDTH (ft), log", "length": 6, "description": "Width, diameter, or second dimension, feet, logistic unit"},
            "3453": {"title": "WIDTH (ft), log", "length": 6, "description": "Width, diameter, or second dimension, feet, logistic unit"},
            "3454": {"title": "WIDTH (ft), log", "length": 6, "description": "Width, diameter, or second dimension, feet, logistic unit"},
            "3455": {"title": "WIDTH (ft), log", "length": 6, "description": "Width, diameter, or second dimension, feet, logistic unit"},
            "3460": {"title": "WIDTH (yd), log", "length": 6, "description": "Width, diameter, or second dimension, yards, logistic unit"},
            "3461": {"title": "WIDTH (yd), log", "length": 6, "description": "Width, diameter, or second dimension, yards, logistic unit"},
            "3462": {"title": "WIDTH (yd), log", "length": 6, "description": "Width, diameter, or second dimension, yards, logistic unit"},
            "3463": {"title": "WIDTH (yd), log", "length": 6, "description": "Width, diameter, or second dimension, yards, logistic unit"},
            "3464": {"title": "WIDTH (yd), log", "length": 6, "description": "Width, diameter, or second dimension, yards, logistic unit"},
            "3465": {"title": "WIDTH (yd), log", "length": 6, "description": "Width, diameter, or second dimension, yards, logistic unit"},
            "3470": {"title": "HEIGHT (in), log", "length": 6, "description": "Depth, thickness, height, or third dimension, inches, logistic unit"},
            "3471": {"title": "HEIGHT (in), log", "length": 6, "description": "Depth, thickness, height, or third dimension, inches, logistic unit"},
            "3472": {"title": "HEIGHT (in), log", "length": 6, "description": "Depth, thickness, height, or third dimension, inches, logistic unit"},
            "3473": {"title": "HEIGHT (in), log", "length": 6, "description": "Depth, thickness, height, or third dimension, inches, logistic unit"},
            "3474": {"title": "HEIGHT (in), log", "length": 6, "description": "Depth, thickness, height, or third dimension, inches, logistic unit"},
            "3475": {"title": "HEIGHT (in), log", "length": 6, "description": "Depth, thickness, height, or third dimension, inches, logistic unit"},
            "3480": {"title": "HEIGHT (ft), log", "length": 6, "description": "Depth, thickness, height, or third dimension, feet, logistic unit"},
            "3481": {"title": "HEIGHT (ft), log", "length": 6, "description": "Depth, thickness, height, or third dimension, feet, logistic unit"},
            "3482": {"title": "HEIGHT (ft), log", "length": 6, "description": "Depth, thickness, height, or third dimension, feet, logistic unit"},
            "3483": {"title": "HEIGHT (ft), log", "length": 6, "description": "Depth, thickness, height, or third dimension, feet, logistic unit"},
            "3484": {"title": "HEIGHT (ft), log", "length": 6, "description": "Depth, thickness, height, or third dimension, feet, logistic unit"},
            "3485": {"title": "HEIGHT (ft), log", "length": 6, "description": "Depth, thickness, height, or third dimension, feet, logistic unit"},
            "3490": {"title": "HEIGHT (yd), log", "length": 6, "description": "Depth, thickness, height, or third dimension, yards, logistic unit"},
            "3491": {"title": "HEIGHT (yd), log", "length": 6, "description": "Depth, thickness, height, or third dimension, yards, logistic unit"},
            "3492": {"title": "HEIGHT (yd), log", "length": 6, "description": "Depth, thickness, height, or third dimension, yards, logistic unit"},
            "3493": {"title": "HEIGHT (yd), log", "length": 6, "description": "Depth, thickness, height, or third dimension, yards, logistic unit"},
            "3494": {"title": "HEIGHT (yd), log", "length": 6, "description": "Depth, thickness, height, or third dimension, yards, logistic unit"},
            "3495": {"title": "HEIGHT (yd), log", "length": 6, "description": "Depth, thickness, height, or third dimension, yards, logistic unit"},
            "3500": {"title": "AREA (in²)", "length": 6, "description": "Area, square inches"},
            "3501": {"title": "AREA (in²)", "length": 6, "description": "Area, square inches"},
            "3502": {"title": "AREA (in²)", "length": 6, "description": "Area, square inches"},
            "3503": {"title": "AREA (in²)", "length": 6, "description": "Area, square inches"},
            "3504": {"title": "AREA (in²)", "length": 6, "description": "Area, square inches"},
            "3505": {"title": "AREA (in²)", "length": 6, "description": "Area, square inches"},
            "3510": {"title": "AREA (ft²)", "length": 6, "description": "Area, square feet, variable measure trade item"},
            "3511": {"title": "AREA (ft²)", "length": 6, "description": "Area, square feet, variable measure trade item"},
            "3512": {"title": "AREA (ft²)", "length": 6, "description": "Area, square feet, variable measure trade item"},
            "3513": {"title": "AREA (ft²)", "length": 6, "description": "Area, square feet, variable measure trade item"},
            "3514": {"title": "AREA (ft²)", "length": 6, "description": "Area, square feet, variable measure trade item"},
            "3515": {"title": "AREA (ft²)", "length": 6, "description": "Area, square feet, variable measure trade item"},
            "3520": {"title": "AREA (yd²)", "length": 6, "description": "Area, square yards, variable measure trade item"},
            "3521": {"title": "AREA (yd²)", "length": 6, "description": "Area, square yards, variable measure trade item"},
            "3522": {"title": "AREA (yd²)", "length": 6, "description": "Area, square yards, variable measure trade item"},
            "3523": {"title": "AREA (yd²)", "length": 6, "description": "Area, square yards, variable measure trade item"},
            "3524": {"title": "AREA (yd²)", "length": 6, "description": "Area, square yards, variable measure trade item"},
            "3525": {"title": "AREA (yd²)", "length": 6, "description": "Area, square yards, variable measure trade item"},
            "3530": {"title": "AREA (in²), log", "length": 6, "description": "Area, square inches, logistic unit"},
            "3531": {"title": "AREA (in²), log", "length": 6, "description": "Area, square inches, logistic unit"},
            "3532": {"title": "AREA (in²), log", "length": 6, "description": "Area, square inches, logistic unit"},
            "3533": {"title": "AREA (in²), log", "length": 6, "description": "Area, square inches, logistic unit"},
            "3534": {"title": "AREA (in²), log", "length": 6, "description": "Area, square inches, logistic unit"},
            "3535": {"title": "AREA (in²), log", "length": 6, "description": "Area, square inches, logistic unit"},
            "3540": {"title": "AREA (ft²), log", "length": 6, "description": "Area, square feet, logistic unit"},
            "3541": {"title": "AREA (ft²), log", "length": 6, "description": "Area, square feet, logistic unit"},
            "3542": {"title": "AREA (ft²), log", "length": 6, "description": "Area, square feet, logistic unit"},
            "3543": {"title": "AREA (ft²), log", "length": 6, "description": "Area, square feet, logistic unit"},
            "3544": {"title": "AREA (ft²), log", "length": 6, "description": "Area, square feet, logistic unit"},
            "3545": {"title": "AREA (ft²), log", "length": 6, "description": "Area, square feet, logistic unit"},
            "3550": {"title": "AREA (yd²), log", "length": 6, "description": "Area, square yards, logistic unit"},
            "3551": {"title": "AREA (yd²), log", "length": 6, "description": "Area, square yards, logistic unit"},
            "3552": {"title": "AREA (yd²), log", "length": 6, "description": "Area, square yards, logistic unit"},
            "3553": {"title": "AREA (yd²), log", "length": 6, "description": "Area, square yards, logistic unit"},
            "3554": {"title": "AREA (yd²), log", "length": 6, "description": "Area, square yards, logistic unit"},
            "3555": {"title": "AREA (yd²), log", "length": 6, "description": "Area, square yards, logistic unit"},
            "3560": {"title": "NET WEIGHT (t oz)", "length": 6, "description": "Net weight, troy ounces, variable measure trade item"},
            "3561": {"title": "NET WEIGHT (t oz)", "length": 6, "description": "Net weight, troy ounces, variable measure trade item"},
            "3562": {"title": "NET WEIGHT (t oz)", "length": 6, "description": "Net weight, troy ounces, variable measure trade item"},
            "3563": {"title": "NET WEIGHT (t oz)", "length": 6, "description": "Net weight, troy ounces, variable measure trade item"},
            "3564": {"title": "NET WEIGHT (t oz)", "length": 6, "description": "Net weight, troy ounces, variable measure trade item"},
            "3565": {"title": "NET WEIGHT (t oz)", "length": 6, "description": "Net weight, troy ounces, variable measure trade item"},
            "3570": {"title": "NET VOLUME (oz)", "length": 6, "description": "Net weight (or volume), ounces, variable measure trade item"},
            "3571": {"title": "NET VOLUME (oz)", "length": 6, "description": "Net weight (or volume), ounces, variable measure trade item"},
            "3572": {"title": "NET VOLUME (oz)", "length": 6, "description": "Net weight (or volume), ounces, variable measure trade item"},
            "3573": {"title": "NET VOLUME (oz)", "length": 6, "description": "Net weight (or volume), ounces, variable measure trade item"},
            "3574": {"title": "NET VOLUME (oz)", "length": 6, "description": "Net weight (or volume), ounces, variable measure trade item"},
            "3575": {"title": "NET VOLUME (oz)", "length": 6, "description": "Net weight (or volume), ounces, variable measure trade item"},
            "3600": {"title": "NET VOLUME (qt)", "length": 6, "description": "Net volume, quarts, variable measure trade item"},
            "3601": {"title": "NET VOLUME (qt)", "length": 6, "description": "Net volume, quarts, variable measure trade item"},
            "3602": {"title": "NET VOLUME (qt)", "length": 6, "description": "Net volume, quarts, variable measure trade item"},
            "3603": {"title": "NET VOLUME (qt)", "length": 6, "description": "Net volume, quarts, variable measure trade item"},
            "3604": {"title": "NET VOLUME (qt)", "length": 6, "description": "Net volume, quarts, variable measure trade item"},
            "3605": {"title": "NET VOLUME (qt)", "length": 6, "description": "Net volume, quarts, variable measure trade item"},
            "3610": {"title": "NET VOLUME (gal.)", "length": 6, "description": "Net volume, gallons U.S., variable measure trade item"},
            "3611": {"title": "NET VOLUME (gal.)", "length": 6, "description": "Net volume, gallons U.S., variable measure trade item"},
            "3612": {"title": "NET VOLUME (gal.)", "length": 6, "description": "Net volume, gallons U.S., variable measure trade item"},
            "3613": {"title": "NET VOLUME (gal.)", "length": 6, "description": "Net volume, gallons U.S., variable measure trade item"},
            "3614": {"title": "NET VOLUME (gal.)", "length": 6, "description": "Net volume, gallons U.S., variable measure trade item"},
            "3615": {"title": "NET VOLUME (gal.)", "length": 6, "description": "Net volume, gallons U.S., variable measure trade item"},
            "3620": {"title": "VOLUME (qt), log", "length": 6, "description": "Logistic volume, quarts"},
            "3621": {"title": "VOLUME (qt), log", "length": 6, "description": "Logistic volume, quarts"},
            "3622": {"title": "VOLUME (qt), log", "length": 6, "description": "Logistic volume, quarts"},
            "3623": {"title": "VOLUME (qt), log", "length": 6, "description": "Logistic volume, quarts"},
            "3624": {"title": "VOLUME (qt), log", "length": 6, "description": "Logistic volume, quarts"},
            "3625": {"title": "VOLUME (qt), log", "length": 6, "description": "Logistic volume, quarts"},
            "3630": {"title": "VOLUME (gal.), log", "length": 6, "description": "Logistic volume, gallons U.S."},
            "3631": {"title": "VOLUME (gal.), log", "length": 6, "description": "Logistic volume, gallons U.S."},
            "3632": {"title": "VOLUME (gal.), log", "length": 6, "description": "Logistic volume, gallons U.S."},
            "3633": {"title": "VOLUME (gal.), log", "length": 6, "description": "Logistic volume, gallons U.S."},
            "3634": {"title": "VOLUME (gal.), log", "length": 6, "description": "Logistic volume, gallons U.S."},
            "3635": {"title": "VOLUME (gal.), log", "length": 6, "description": "Logistic volume, gallons U.S."},
            "3640": {"title": "VOLUME (in³)", "length": 6, "description": "Net volume, cubic inches, variable measure trade item"},
            "3641": {"title": "VOLUME (in³)", "length": 6, "description": "Net volume, cubic inches, variable measure trade item"},
            "3642": {"title": "VOLUME (in³)", "length": 6, "description": "Net volume, cubic inches, variable measure trade item"},
            "3643": {"title": "VOLUME (in³)", "length": 6, "description": "Net volume, cubic inches, variable measure trade item"},
            "3644": {"title": "VOLUME (in³)", "length": 6, "description": "Net volume, cubic inches, variable measure trade item"},
            "3645": {"title": "VOLUME (in³)", "length": 6, "description": "Net volume, cubic inches, variable measure trade item"},
            "3650": {"title": "VOLUME (ft³)", "length": 6, "description": "Net volume, cubic feet, variable measure trade item"},
            "3651": {"title": "VOLUME (ft³)", "length": 6, "description": "Net volume, cubic feet, variable measure trade item"},
            "3652": {"title": "VOLUME (ft³)", "length": 6, "description": "Net volume, cubic feet, variable measure trade item"},
            "3653": {"title": "VOLUME (ft³)", "length": 6, "description": "Net volume, cubic feet, variable measure trade item"},
            "3654": {"title": "VOLUME (ft³)", "length": 6, "description": "Net volume, cubic feet, variable measure trade item"},
            "3655": {"title": "VOLUME (ft³)", "length": 6, "description": "Net volume, cubic feet, variable measure trade item"},
            "3660": {"title": "VOLUME (yd³)", "length": 6, "description": "Net volume, cubic yards, variable measure trade item"},
            "3661": {"title": "VOLUME (yd³)", "length": 6, "description": "Net volume, cubic yards, variable measure trade item"},
            "3662": {"title": "VOLUME (yd³)", "length": 6, "description": "Net volume, cubic yards, variable measure trade item"},
            "3663": {"title": "VOLUME (yd³)", "length": 6, "description": "Net volume, cubic yards, variable measure trade item"},
            "3664": {"title": "VOLUME (yd³)", "length": 6, "description": "Net volume, cubic yards, variable measure trade item"},
            "3665": {"title": "VOLUME (yd³)", "length": 6, "description": "Net volume, cubic yards, variable measure trade item"},
            "3670": {"title": "VOLUME (in³), log", "length": 6, "description": "Logistic volume, cubic inches"},
            "3671": {"title": "VOLUME (in³), log", "length": 6, "description": "Logistic volume, cubic inches"},
            "3672": {"title": "VOLUME (in³), log", "length": 6, "description": "Logistic volume, cubic inches"},
            "3673": {"title": "VOLUME (in³), log", "length": 6, "description": "Logistic volume, cubic inches"},
            "3674": {"title": "VOLUME (in³), log", "length": 6, "description": "Logistic volume, cubic inches"},
            "3675": {"title": "VOLUME (in³), log", "length": 6, "description": "Logistic volume, cubic inches"},
            "3680": {"title": "VOLUME (ft³), log", "length": 6, "description": "Logistic volume, cubic feet"},
            "3681": {"title": "VOLUME (ft³), log", "length": 6, "description": "Logistic volume, cubic feet"},
            "3682": {"title": "VOLUME (ft³), log", "length": 6, "description": "Logistic volume, cubic feet"},
            "3683": {"title": "VOLUME (ft³), log", "length": 6, "description": "Logistic volume, cubic feet"},
            "3684": {"title": "VOLUME (ft³), log", "length": 6, "description": "Logistic volume, cubic feet"},
            "3685": {"title": "VOLUME (ft³), log", "length": 6, "description": "Logistic volume, cubic feet"},
            "3690": {"title": "VOLUME (yd³), log", "length": 6, "description": "Logistic volume, cubic yards"},
            "3691": {"title": "VOLUME (yd³), log", "length": 6, "description": "Logistic volume, cubic yards"},
            "3692": {"title": "VOLUME (yd³), log", "length": 6, "description": "Logistic volume, cubic yards"},
            "3693": {"title": "VOLUME (yd³), log", "length": 6, "description": "Logistic volume, cubic yards"},
            "3694": {"title": "VOLUME (yd³), log", "length": 6, "description": "Logistic volume, cubic yards"},
            "3695": {"title": "VOLUME (yd³), log", "length": 6, "description": "Logistic volume, cubic yards"},
            "37": {"title": "COUNT", "length": None, "description": "Count of trade items or trade item pieces contained in a logistic unit"},
            "3900": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3901": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3902": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3903": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3904": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3905": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3906": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3907": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3908": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3909": {"title": "AMOUNT", "length": None, "description": "Amount payable or coupon value - Single monetary area"},
            "3910": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3911": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3912": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3913": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3914": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3915": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3916": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3917": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3918": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3919": {"title": "AMOUNT", "length": None, "description": "Amount payable and ISO currency code"},
            "3920": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3921": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3922": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3923": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3924": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3925": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3926": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3927": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3928": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3929": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item – Single monetary area"},
            "3930": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3931": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3932": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3933": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3934": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3935": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3936": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3937": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3938": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3939": {"title": "PRICE", "length": None, "description": "Amount payable for a variable measure trade item and ISO currency code"},
            "3940": {"title": "PRCNT OFF", "length": None, "description": "Percentage discount of a coupon"},
            "3941": {"title": "PRCNT OFF", "length": None, "description": "Percentage discount of a coupon"},
            "3942": {"title": "PRCNT OFF", "length": None, "description": "Percentage discount of a coupon"},
            "3943": {"title": "PRCNT OFF", "length": None, "description": "Percentage discount of a coupon"},
            "3950": {"title": "PRICE/UoM", "length": None, "description": "Amount Payable per unit of measure single monetary area (variable measure trade item)"},
            "3951": {"title": "PRICE/UoM", "length": None, "description": "Amount Payable per unit of measure single monetary area (variable measure trade item)"},
            "3952": {"title": "PRICE/UoM", "length": None, "description": "Amount Payable per unit of measure single monetary area (variable measure trade item)"},
            "3953": {"title": "PRICE/UoM", "length": None, "description": "Amount Payable per unit of measure single monetary area (variable measure trade item)"},
            "3954": {"title": "PRICE/UoM", "length": None, "description": "Amount Payable per unit of measure single monetary area (variable measure trade item)"},
            "3955": {"title": "PRICE/UoM", "length": None, "description": "Amount Payable per unit of measure single monetary area (variable measure trade item)"},
            "400": {"title": "ORDER NUMBER", "length": None, "description": "Customer’s purchase order number"},
            "401": {"title": "GINC", "length": None, "description": "Global Identification Number for Consignment (GINC)"},
            "402": {"title": "GSIN", "length": None, "description": "Global Shipment Identification Number (GSIN)"},
            "403": {"title": "ROUTE", "length": None, "description": "Routing code"},
            "410": {"title": "SHIP TO LOC", "length": None, "description": "Ship to / Deliver to Global Location Number (GLN)"},
            "411": {"title": "BILL TO", "length": None, "description": "Bill to / Invoice to Global Location Number (GLN)"},
            "412": {"title": "PURCHASE FROM", "length": None, "description": "Purchased from Global Location Number (GLN)"},
            "413": {"title": "SHIP FOR LOC", "length": None, "description": "Ship for / Deliver for - Forward to Global Location Number (GLN)"},
            "414": {"title": "Loc No.", "length": None, "description": "Identification of a physical location - Global Location Number (GLN)"},
            "415": {"title": "PAY TO", "length": None, "description": "Global Location Number (GLN) of the invoicing party"},
            "416": {"title": "PROD/SERV LOC", "length": None, "description": "Global Location Number (GLN) of the production or service location"},
            "417": {"title": "PARTY", "length": None, "description": "Party Global Location Number (GLN)"},
            "420": {"title": "SHIP TO POST", "length": None, "description": "Ship to / Deliver to postal code within a single postal authority"},
            "421": {"title": "SHIP TO POST", "length": None, "description": "Ship to / Deliver to postal code with ISO country code"},
            "422": {"title": "ORIGIN", "length": None, "description": "Country of origin of a trade item"},
            "423": {"title": "COUNTRY - INITIAL PROCESS", "length": None, "description": "Country of initial processing"},
            "424": {"title": "COUNTRY - PROCESS", "length": None, "description": "Country of processing"},
            "425": {"title": "COUNTRY - DISASSEMBLY", "length": None, "description": "Country of disassembly"},
            "426": {"title": "COUNTRY - FULL PROCESS", "length": None, "description": "Country covering full process chain"},
            "427": {"title": "ORIGIN SUBDIVISION", "length": None, "description": "Country subdivision of origin code for a trade item"},
            "4300": {"title": "SHIP TO COMP", "length": None, "description": "Ship-to / Deliver-to Company name"},
            "4301": {"title": "SHIP TO NAME", "length": None, "description": "Ship-to / Deliver-to contact name"},
            "4302": {"title": "SHIP TO ADD1", "length": None, "description": "Ship-to / Deliver-to address line 1"},
            "4303": {"title": "SHIP TO ADD2", "length": None, "description": "Ship-to / Deliver-to address line 2"},
            "4304": {"title": "SHIP TO SUB", "length": None, "description": "Ship-to / Deliver-to suburb"},
            "4305": {"title": "SHIP TO LOC", "length": None, "description": "Ship-to / Deliver-to locality"},
            "4306": {"title": "SHIP TO REG", "length": None, "description": "Ship-to / Deliver-to region"},
            "4307": {"title": "SHIP TO COUNTRY", "length": None, "description": "Ship-to / Deliver-to country code"},
            "4308": {"title": "SHIP TO PHONE", "length": None, "description": "Ship-to / Deliver-to telephone number"},
            "4309": {"title": "SHIP TO GEO", "length": None, "description": "Ship-to / Deliver-to GEO location"},
            "4310": {"title": "RTN TO COMP", "length": None, "description": "Return-to company name"},
            "4311": {"title": "RTN TO NAME", "length": None, "description": "Return-to contact"},
            "4312": {"title": "RTN TO ADD1", "length": None, "description": "Return-to address line 1"},
            "4313": {"title": "RTN TO ADD2", "length": None, "description": "Return-to address line 2"},
            "4314": {"title": "RTN TO SUB", "length": None, "description": "Return-to suburb"},
            "4315": {"title": "RTN TO LOC", "length": None, "description": "Return-to locality"},
            "4316": {"title": "RTN TO REG", "length": None, "description": "Return-to region"},
            "4317": {"title": "RTN TO COUNTRY", "length": None, "description": "Return-to country code"},
            "4318": {"title": "RTN TO POST", "length": None, "description": "Return-to postal code"},
            "4319": {"title": "RTN TO PHONE", "length": None, "description": "Return-to telephone number"},
            "4320": {"title": "SRV DESCRIPTION", "length": None, "description": "Service code description"},
            "4321": {"title": "DANGEROUS GOODS", "length": None, "description": "Dangerous goods flag"},
            "4322": {"title": "AUTH LEAVE", "length": None, "description": "Authority to leave"},
            "4323": {"title": "SIG REQUIRED", "length": None, "description": "Signature required flag"},
            "4324": {"title": "NBEF DEL DT", "length": None, "description": "Not before delivery date time"},
            "4325": {"title": "NAFT DEL DT", "length": None, "description": "Not after delivery date time"},
            "4326": {"title": "REL DATE", "length": None, "description": "Release date"},
            "4330": {"title": "MAX TEMP F", "length": None, "description": "Maximum temperature in Fahrenheit"},
            "4331": {"title": "MAX TEMP C", "length": None, "description": "Maximum temperature in Celsius"},
            "4332": {"title": "MIN TEMP F", "length": None, "description": "Minimum temperature in Fahrenheit"},
            "4333": {"title": "MIN TEMP C", "length": None, "description": "Minimum temperature in Celsius"},
            "7001": {"title": "NSN", "length": None, "description": "NATO Stock Number (NSN)"},
            "7002": {"title": "MEAT CUT", "length": None, "description": "UNECE meat carcasses and cuts classification"},
            "7003": {"title": "EXPIRY TIME", "length": None, "description": "Expiration date and time"},
            "7004": {"title": "ACTIVE POTENCY", "length": None, "description": "Active potency"},
            "7005": {"title": "CATCH AREA", "length": None, "description": "Catch area"},
            "7006": {"title": "FIRST FREEZE DATE", "length": None, "description": "First freeze date"},
            "7007": {"title": "HARVEST DATE", "length": None, "description": "Harvest date"},
            "7008": {"title": "AQUATIC SPECIES", "length": None, "description": "Species for fishery purposes"},
            "7009": {"title": "FISHING GEAR TYPE", "length": None, "description": "Fishing gear type"},
            "7010": {"title": "PROD METHOD", "length": None, "description": "Production method"},
            "7011": {"title": "TEST BY DATE", "length": None, "description": "Test by date"},
            "7020": {"title": "REFURB LOT", "length": None, "description": "Refurbishment lot ID"},
            "7021": {"title": "FUNC STAT", "length": None, "description": "Functional status"},
            "7022": {"title": "REV STAT", "length": None, "description": "Revision status"},
            "7023": {"title": "GIAI - ASSEMBLY", "length": None, "description": "Global Individual Asset Identifier (GIAI) of an assembly"},
            "7030": {"title": "PROCESSOR # 0", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7031": {"title": "PROCESSOR # 1", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7032": {"title": "PROCESSOR # 2", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7033": {"title": "PROCESSOR # 3", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7034": {"title": "PROCESSOR # 4", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7035": {"title": "PROCESSOR # 5", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7036": {"title": "PROCESSOR # 6", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7037": {"title": "PROCESSOR # 7", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7038": {"title": "PROCESSOR # 8", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7039": {"title": "PROCESSOR # 9", "length": None, "description": "Number of processor with three-digit ISO country code"},
            "7040": {"title": "UIC+EXT", "length": None, "description": "GS1 UIC with Extension 1 and Importer index"},
            "710": {"title": "NHRN PZN", "length": None, "description": "National Healthcare Reimbursement Number (NHRN) - Germany PZN"},
            "711": {"title": "NHRN CIP", "length": None, "description": "National Healthcare Reimbursement Number (NHRN) - France CIP"},
            "712": {"title": "NHRN CN", "length": None, "description": "National Healthcare Reimbursement Number (NHRN) - Spain CN"},
            "713": {"title": "NHRN DRN", "length": None, "description": "National Healthcare Reimbursement Number (NHRN) - Brasil DRN"},
            "714": {"title": "NHRN AIM", "length": None, "description": "National Healthcare Reimbursement Number (NHRN) - Portugal AIM"},
            "715": {"title": "NHRN NDC", "length": None, "description": "National Healthcare Reimbursement Number (NHRN) - United States of America NDC"},
            "7230": {"title": "CERT # 0", "length": None, "description": "Certification reference"},
            "7231": {"title": "CERT # 1", "length": None, "description": "Certification reference"},
            "7232": {"title": "CERT # 2", "length": None, "description": "Certification reference"},
            "7233": {"title": "CERT # 3", "length": None, "description": "Certification reference"},
            "7234": {"title": "CERT # 4", "length": None, "description": "Certification reference"},
            "7235": {"title": "CERT # 5", "length": None, "description": "Certification reference"},
            "7236": {"title": "CERT # 6", "length": None, "description": "Certification reference"},
            "7237": {"title": "CERT # 7", "length": None, "description": "Certification reference"},
            "7238": {"title": "CERT # 8", "length": None, "description": "Certification reference"},
            "7239": {"title": "CERT # 9", "length": None, "description": "Certification reference"},
            "7240": {"title": "PROTOCOL", "length": None, "description": "Protocol ID"},
            "7241": {"title": "AIDC MEDIA TYPE", "length": None, "description": "AIDC media type"},
            "7242": {"title": "VCN", "length": None, "description": "Version Control Number (VCN)"},
            "8001": {"title": "DIMENSIONS", "length": None, "description": "Roll products (width, length, core diameter, direction, splices)"},
            "8002": {"title": "CMT NO.", "length": None, "description": "Cellular mobile telephone identifier"},
            "8003": {"title": "GRAI", "length": None, "description": "Global Returnable Asset Identifier (GRAI)"},
            "8004": {"title": "GIAI", "length": None, "description": "Global Individual Asset Identifier (GIAI)"},
            "8005": {"title": "PRICE PER UNIT", "length": None, "description": "Price per unit of measure"},
            "8006": {"title": "ITIP", "length": None, "description": "Identification of an individual trade item (ITIP) piece"},
            "8007": {"title": "IBAN", "length": None, "description": "International Bank Account Number (IBAN)"},
            "8008": {"title": "PROD TIME", "length": None, "description": "Date and time of production"},
            "8009": {"title": "OPTSEN", "length": None, "description": "Optically Readable Sensor Indicator"},
            "8010": {"title": "CPID", "length": None, "description": "Component/Part Identifier (CPID)"},
            "8011": {"title": "CPID SERIAL", "length": None, "description": "Component/Part Identifier serial number (CPID SERIAL)"},
            "8012": {"title": "VERSION", "length": None, "description": "Software version"},
            "8013": {"title": "GMN", "length": None, "description": "Global Model Number (GMN)"},
            "8017": {"title": "GSRN - PROVIDER", "length": None, "description": "Global Service Relation Number (GSRN) to identify the relationship between an organisation offering services and the provider of services"},
            "8018": {"title": "GSRN - RECIPIENT", "length": None, "description": "Global Service Relation Number (GSRN) to identify the relationship between an organisation offering services and the recipient of services"},
            "8019": {"title": "SRIN", "length": None, "description": "Service Relation Instance Number (SRIN)"},
            "8020": {"title": "Ref No.", "length": None, "description": "Payment slip reference number"},
            "8026": {"title": "ITIP CONTENT", "length": None, "description": "Identification of pieces of a trade item (ITIP) contained in a logistic unit"},
            "8030": {"title": "DIGSIG", "length": None, "description": "Digital Signature (DigSig)"},
            "8110": {"title": "", "length": None, "description": "Coupon code identification for use in North America"},
            "8111": {"title": "POINTS", "length": None, "description": "Loyalty points of a coupon"},
            "8112": {"title": "", "length": None, "description": "Positive offer file coupon code identification for use in North America"},
            "8200": {"title": "PRODUCT URL", "length": None, "description": "Extended Packaging URL"},
            "90": {"title": "INTERNAL", "length": None, "description": "Information mutually agreed between trading partners"},
            "91": {"title": "INTERNAL", "length": None, "description": "Company internal information"},
            "92": {"title": "INTERNAL", "length": None, "description": "Company internal information"},
            "93": {"title": "INTERNAL", "length": None, "description": "Company internal information"},
            "94": {"title": "INTERNAL", "length": None, "description": "Company internal information"},
            "95": {"title": "INTERNAL", "length": None, "description": "Company internal information"},
            "96": {"title": "INTERNAL", "length": None, "description": "Company internal information"},
            "97": {"title": "INTERNAL", "length": None, "description": "Company internal information"},
            "98": {"title": "INTERNAL", "length": None, "description": "Company internal information"},
            "99": {"title": "INTERNAL", "length": None, "description": "Company internal information"}
        }
        return ai_definitions

    def parse_ai(self, ai_code: str) -> Dict[str, any]:
        # Parsing logic to handle the AI code and its definition
        if ai_code in self.ai_definitions:
            return self.ai_definitions[ai_code]
        else:
            return {"error": "AI code not recognized"}
        
    def parse_gs1_barcode(self, barcode_data: str) -> List[Dict[str, any]]:
        parsed_data = []
        while barcode_data:
            ai, value, barcode_data = self.extract_next_ai(barcode_data)
            if ai:
                ai_info = self.parse_ai(ai)
                parsed_data.append({
                    "ai": ai,
                    "value": value,
                    "title": ai_info.get("title", ""),
                    "description": ai_info.get("description", "")
                })
            else:
                break
        return parsed_data

    def extract_next_ai(self, data: str) -> Tuple[str, str, str]:
        for length in [4, 3, 2]:
            ai = data[:length]
            if ai in self.ai_definitions:
                ai_def = self.ai_definitions[ai]
                if ai_def["length"]:
                    value = data[length:length + ai_def["length"]]
                    remaining = data[length + ai_def["length"]:]
                else:
                    separator_index = data.find('#', length)
                    if separator_index == -1:
                        value = data[length:]
                        remaining = ''
                    else:
                        value = data[length:separator_index]
                        remaining = data[separator_index + 1:]
                return ai, value, remaining
        return None, None, data

# Example usage
handler = GS1AIHandler()
print(handler.parse_ai("01"))  # Outputs the definition for GTIN
